# Generated by Django 5.0.4 on 2024-06-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuizResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("question1", models.CharField(max_length=100)),
                ("question2", models.CharField(max_length=100)),
                ("question3", models.CharField(max_length=100)),
                ("question4", models.CharField(max_length=100)),
                ("question5", models.CharField(max_length=100)),
            ],
        ),
    ]
