from django.db import models

class QuizResponse(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    question1 = models.CharField(max_length=100)
    question2 = models.CharField(max_length=100)
    question3 = models.CharField(max_length=100)
    question4 = models.CharField(max_length=100)
    question5 = models.CharField(max_length=100)
    question6 = models.CharField(max_length=100)
    question7 = models.CharField(max_length=100)
    question8 = models.CharField(max_length=100)
    question9 = models.CharField(max_length=100)
    question10 = models.CharField(max_length=100)
    question11 = models.CharField(max_length=100)
    question12 = models.CharField(max_length=100)
    question13 = models.CharField(max_length=100)
    question14 = models.CharField(max_length=100)
    question15 = models.CharField(max_length=100)
    question16 = models.CharField(max_length=100)
    question17 = models.CharField(max_length=100)
    question18 = models.CharField(max_length=100)
    question19 = models.CharField(max_length=100)
    question20 = models.CharField(max_length=100)
